#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "loki"
name = "Loki + Promtail"
description.en = "Set of components that can be composed into a fully featured logging stack"
description.fr = "Ensemble de composants qui peuvent être composés pour former une pile de journalisation complète"

version = "3.0.0~ynh1"

maintainers = ["fflorent"]

[upstream]
license = "AGPL-3.0"
website = "https://grafana.com/docs/loki/latest/"
admindoc = "https://grafana.com/docs/loki/latest/"
code = "https://github.com/grafana/loki"
cpe = "cpe:2.3:a:grafana:loki"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "armhf", "arm64"]
multi_instance = true

ldap = "not_relevant"

sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

[resources]
    [resources.sources]
    [resources.sources.loki]
    amd64.url = "https://github.com/grafana/loki/releases/download/v3.1.0/loki-linux-amd64.zip"
    amd64.sha256 = "bbcc58f0895e6119ba9c6ee41e44b1cf19186db4e920256462dc062c6a7bc632"
    armhf.url = "https://github.com/grafana/loki/releases/download/v3.1.0/loki-linux-arm.zip"
    armhf.sha256 = "68c92867eafc24079ca4f66533422755564f900a6db8962691c37da74bb4af08"
    arm64.url = "https://github.com/grafana/loki/releases/download/v3.1.0/loki-linux-arm64.zip"
    arm64.sha256 = "f22f0515dfe0ad91802e5a5af577a2f94a6b4edae374e55fe2bb31b048e227c8"
    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^loki-linux-amd64.zip$"
    autoupdate.asset.armhf = "^loki-linux-arm.zip$"
    autoupdate.asset.arm64 = "^loki-linux-arm64.zip$"

    [resources.sources.promtail]
    amd64.url = "https://github.com/grafana/loki/releases/download/v3.1.0/promtail-linux-amd64.zip"
    amd64.sha256 = "4efd23367ae8d26025fb36fb32476de6d23677231ba58590e829afab7c51b23f"
    armhf.url = "https://github.com/grafana/loki/releases/download/v3.1.0/promtail-linux-arm.zip"
    armhf.sha256 = "6ba3380d3442d8d2de24a6f4486e70e2056df1d699c2d6b60489e1c79ef037f9"
    arm64.url = "https://github.com/grafana/loki/releases/download/v3.1.0/promtail-linux-arm64.zip"
    arm64.sha256 = "d6bd97d65078d15354dddad704e358279819a412448bafc7dbf7679e14e6db88"
    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^promtail-linux-amd64.zip$"
    autoupdate.asset.armhf = "^promtail-linux-arm.zip$"
    autoupdate.asset.arm64 = "^promtail-linux-arm64.zip$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]

    [resources.ports]
    http.default = 3100
    grpc.default = 9096
    promtail.default = 9080
