#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "loki"
name = "Loki + Promtail"
description.en = "Set of components that can be composed into a fully featured logging stack"
description.fr = "Ensemble de composants qui peuvent être composés pour former une pile de journalisation complète"

version = "3.5.0~ynh1"

maintainers = ["fflorent"]

[upstream]
license = "AGPL-3.0"
website = "https://grafana.com/docs/loki/latest/"
admindoc = "https://grafana.com/docs/loki/latest/"
code = "https://github.com/grafana/loki"
cpe = "cpe:2.3:a:grafana:loki"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "armhf", "arm64"]
multi_instance = true

ldap = "not_relevant"

sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

[resources]
    [resources.sources]
    [resources.sources.main]
    amd64.url = "https://github.com/grafana/loki/releases/download/v3.5.0/loki-linux-amd64.zip"
    amd64.sha256 = "45131e8b799c46ad58a94fad6bf5e0d508ed56fb016d45a6eade7801b95377de"
    armhf.url = "https://github.com/grafana/loki/releases/download/v3.5.0/loki-linux-arm.zip"
    armhf.sha256 = "264df2dda6579fe6a424bf1ea7169b2bdade3d35fe3c8e2c89b81377f1ebe752"
    arm64.url = "https://github.com/grafana/loki/releases/download/v3.5.0/loki-linux-arm64.zip"
    arm64.sha256 = "bd2354ac19de80266b970171e62e203de9b751739475e35513b4f2dd1438d3aa"
    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^loki-linux-amd64.zip$"
    autoupdate.asset.armhf = "^loki-linux-arm.zip$"
    autoupdate.asset.arm64 = "^loki-linux-arm64.zip$"

    [resources.sources.promtail]
    amd64.url = "https://github.com/grafana/loki/releases/download/v3.5.0/promtail-linux-amd64.zip"
    amd64.sha256 = "a67d6a0b0e6e31bb56e76ad7aea08000d7c9bd87b470a1040165c968aaead8d3"
    armhf.url = "https://github.com/grafana/loki/releases/download/v3.5.0/promtail-linux-arm.zip"
    armhf.sha256 = "d6926efe448310c2667acc93036f4aa3dd4a51d86b829f15c7144cff0a6ade58"
    arm64.url = "https://github.com/grafana/loki/releases/download/v3.5.0/promtail-linux-arm64.zip"
    arm64.sha256 = "09afc0725c62212cdf69487ed901394c8e6d1f3c5937677d43f69ede0fc30a5c"
    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^promtail-linux-amd64.zip$"
    autoupdate.asset.armhf = "^promtail-linux-arm.zip$"
    autoupdate.asset.arm64 = "^promtail-linux-arm64.zip$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]

    [resources.ports]
    http.default = 3100
    grpc.default = 9096
    promtail.default = 9080
