#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "loki"
name = "Loki + Promtail"
description.en = "Grafana Loki is a set of components that can be composed into a fully featured logging stack."
description.fr = "Grafana Loki est un ensemble de composants qui peuvent être composés pour former une pile de journalisation complète."

version = "2.8.4~ynh2"

maintainers = ["fflorent"]

[upstream]
license = "AGPL-3.0"
website = "https://grafana.com/docs/loki/latest/"
admindoc = "https://grafana.com/docs/loki/latest/"
code = "https://github.com/grafana/loki"
cpe = "cpe:2.3:a:grafana:loki"

[integration]
yunohost = ">= 11.0.0"
architectures = ["amd64", "arm64"]
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

[resources]
    [resources.sources]
    [resources.sources.loki]
    amd64.url = "https://github.com/grafana/loki/releases/download/v2.9.4/loki-linux-amd64.zip"
    amd64.sha256 = "6da1fcb0a64004373c47517f9e072637fb6b697790d8f295d0b423f3dd5d334b"
    arm64.url = "https://github.com/grafana/loki/releases/download/v2.9.4/loki-linux-arm64.zip"
    arm64.sha256 = "92d1ea859044a9fc8d5916cb36a464545fec7bd70a7471c65cd21cc0f1834493"
    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "loki-linux-amd64"
    autoupdate.asset.arm64 = "loki-linux-arm64"

    [resources.sources.promtail]
    amd64.url = "https://github.com/grafana/loki/releases/download/v2.9.4/promtail-linux-amd64.zip"
    amd64.sha256 = "ff40a0717b9901ad42f4fea3c1ab307efc9d267266d7abbbcbabce2144e4e0f4"
    arm64.url = "https://github.com/grafana/loki/releases/download/v2.9.4/promtail-linux-arm64.zip"
    arm64.sha256 = "1e7ae650d522c1a897fe38a82708fbeb7d4eaad9873ec641b0ce421595865010"
    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "promtail-linux-amd64"
    autoupdate.asset.arm64 = "promtail-linux-arm64"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]

    [resources.ports]
    http.default = 3100
    grpc.default = 9096
    promtail.default = 9080
