#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "loki"
name = "Loki + Promtail"
description.en = "Grafana Loki is a set of components that can be composed into a fully featured logging stack."
description.fr = "Grafana Loki est un ensemble de composants qui peuvent être composés pour former une pile de journalisation complète."

version = "2.8.4~ynh3"

maintainers = ["fflorent"]

[upstream]
license = "AGPL-3.0"
website = "https://grafana.com/docs/loki/latest/"
admindoc = "https://grafana.com/docs/loki/latest/"
code = "https://github.com/grafana/loki"
cpe = "cpe:2.3:a:grafana:loki"

[integration]
yunohost = ">= 11.0.0"
architectures = ["amd64", "arm64"]
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

[resources]
    [resources.sources]
    [resources.sources.loki]
    amd64.url = "https://github.com/grafana/loki/releases/download/v2.9.5/loki-linux-amd64.zip"
    amd64.sha256 = "9d919a55e7a2dbaeab46e777a0589d7e304c71fed011f989143883cbc887e348"
    arm64.url = "https://github.com/grafana/loki/releases/download/v2.9.5/loki-linux-arm64.zip"
    arm64.sha256 = "491833bf201c55388b82c3d1f583a9d4426c1b778ed3dc710cd67c8cbbbb67bb"
    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "loki-linux-amd64"
    autoupdate.asset.arm64 = "loki-linux-arm64"

    [resources.sources.promtail]
    amd64.url = "https://github.com/grafana/loki/releases/download/v2.9.5/promtail-linux-amd64.zip"
    amd64.sha256 = "e444bcff2d6677d284350819d3d1b7b473a1699357689230254fbc602b28dac7"
    arm64.url = "https://github.com/grafana/loki/releases/download/v2.9.5/promtail-linux-arm64.zip"
    arm64.sha256 = "b23bd750dc5f6a76d808826ebc9d3c8b3540adb329578b650571a10d2be348b8"
    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "promtail-linux-amd64"
    autoupdate.asset.arm64 = "promtail-linux-arm64"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]

    [resources.ports]
    http.default = 3100
    grpc.default = 9096
    promtail.default = 9080
